import { ApplicationConfig, provideBrowserGlobalErrorListeners, provideZoneChangeDetection } from '@angular/core';
import { PreloadAllModules, provideRouter, withPreloading } from '@angular/router';
import { HttpClient, provideHttpClient, withFetch } from '@angular/common/http';
import {
  LucideArmchair,
  LucideArrowLeft,
  LucideArrowRight,
  LucideBan,
  LucideBell,
  LucideBookOpen,
  LucideBookOpenText,
  LucideBookmark,
  LucideBriefcaseBusiness,
  LucideBrushCleaning,
  LucideBuilding2,
  LucideCalendarOff,
  LucideCalendarDays,
  LucideCalendarClock,
  LucideCalendarPlus,
  LucideCheck,
  LucideChartNoAxesColumn,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircle,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleDot,
  LucideCirclePlus,
  LucideCircleStop,
  LucideCircleX,
  LucideClipboard,
  LucideClipboardCheck,
  LucideClipboardCopy,
  LucideClipboardList,
  LucideClipboardPaste,
  LucideClock3,
  LucideCloudDownload,
  LucideColumns2,
  LucideColumns3,
  LucideCopy,
  LucideCreditCard,
  LucideDownload,
  LucideEraser,
  LucideExternalLink,
  LucideExpand,
  LucideFileDown,
  LucideFileSpreadsheet,
  LucideFileText,
  LucideFingerprintPattern,
  LucideFlag,
  LucideFolder,
  LucideFolderOpen,
  LucideGauge,
  LucideGlobe,
  LucideHeart,
  LucideHistory,
  LucideHouse,
  LucideInfo,
  LucideLeaf,
  LucideLibraryBig,
  LucideListIndentDecrease,
  LucideListIndentIncrease,
  LucideLightbulb,
  LucideLink,
  LucideLayoutGrid,
  LucideList,
  LucideListChecks,
  LucideListTodo,
  LucideListOrdered,
  LucideLoaderCircle,
  LucideLockKeyhole,
  LucideLogIn,
  LucideLogOut,
  LucideMailOpen,
  LucideMapPin,
  LucideMessageCircle,
  LucideMenu,
  LucideMinus,
  LucideMoveRight,
  LucideNotebookPen,
  LucidePaintbrush,
  LucidePalette,
  LucidePalmtree,
  LucidePanelTop,
  LucidePartyPopper,
  LucidePause,
  LucidePencil,
  LucidePlay,
  LucidePlus,
  LucidePresentation,
  LucidePrinter,
  LucideRefreshCw,
  LucideRepeat2,
  LucideRocket,
  LucideRotateCcw,
  LucideRotateCw,
  LucideRoute,
  LucideRows3,
  LucideSave,
  LucideSearch,
  LucideSend,
  LucideSettings,
  LucideShieldCheck,
  LucideSparkles,
  LucideSquare,
  LucideSquareCheck,
  LucideSquarePen,
  LucideStar,
  LucideStickyNote,
  LucideTable,
  LucideTarget,
  LucideText,
  LucideTicket,
  LucideTimer,
  LucideTrainTrack,
  LucideTrainFront,
  LucideTrash2,
  LucideTriangleAlert,
  LucideTrophy,
  LucideUndo2,
  LucideUpload,
  LucideWifiOff,
  LucideWrench,
  LucideX,
  LucideZap,
  LucideKeyRound,
  provideLucideIcons,
} from '@lucide/angular';

import { MERMAID_OPTIONS, provideMarkdown, MARKED_OPTIONS } from 'ngx-markdown';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(withFetch()),
    provideLucideIcons(
      LucideArmchair,
      LucideArrowLeft,
      LucideArrowRight,
      LucideBan,
      LucideBell,
      LucideBookOpen,
      LucideBookOpenText,
      LucideBookmark,
      LucideBriefcaseBusiness,
      LucideBrushCleaning,
      LucideBuilding2,
      LucideCalendarOff,
      LucideCalendarDays,
      LucideCalendarClock,
      LucideCalendarPlus,
      LucideCheck,
      LucideChartNoAxesColumn,
      LucideChevronDown,
      LucideChevronLeft,
      LucideChevronRight,
      LucideChevronUp,
      LucideCircle,
      LucideCircleAlert,
      LucideCircleCheck,
      LucideCircleDot,
      LucideCirclePlus,
      LucideCircleStop,
      LucideCircleX,
      LucideClipboard,
      LucideClipboardCheck,
      LucideClipboardCopy,
      LucideClipboardList,
      LucideClipboardPaste,
      LucideClock3,
      LucideCloudDownload,
      LucideColumns2,
      LucideColumns3,
      LucideCopy,
      LucideCreditCard,
      LucideDownload,
      LucideEraser,
      LucideExternalLink,
      LucideExpand,
      LucideFileDown,
      LucideFileSpreadsheet,
      LucideFileText,
      LucideFingerprintPattern,
      LucideFlag,
      LucideFolder,
      LucideFolderOpen,
      LucideGauge,
      LucideGlobe,
      LucideHeart,
      LucideHistory,
      LucideHouse,
      LucideInfo,
      LucideLeaf,
      LucideLibraryBig,
      LucideListIndentDecrease,
      LucideListIndentIncrease,
      LucideLightbulb,
      LucideLink,
      LucideLayoutGrid,
      LucideList,
      LucideListChecks,
      LucideListTodo,
      LucideListOrdered,
      LucideLoaderCircle,
      LucideLockKeyhole,
      LucideLogIn,
      LucideLogOut,
      LucideMailOpen,
      LucideMapPin,
      LucideMessageCircle,
      LucideMenu,
      LucideMinus,
      LucideMoveRight,
      LucideNotebookPen,
      LucidePaintbrush,
      LucidePalette,
      LucidePalmtree,
      LucidePanelTop,
      LucidePartyPopper,
      LucidePause,
      LucidePencil,
      LucidePlay,
      LucidePlus,
      LucidePresentation,
      LucidePrinter,
      LucideRefreshCw,
      LucideRepeat2,
      LucideRocket,
      LucideRotateCcw,
      LucideRotateCw,
      LucideRoute,
      LucideRows3,
      LucideSave,
      LucideSearch,
      LucideSend,
      LucideSettings,
      LucideShieldCheck,
      LucideSparkles,
      LucideSquare,
      LucideSquareCheck,
      LucideSquarePen,
      LucideStar,
      LucideStickyNote,
      LucideTable,
      LucideTarget,
      LucideText,
      LucideTicket,
      LucideTimer,
      LucideTrainTrack,
      LucideTrainFront,
      LucideTrash2,
      LucideTriangleAlert,
      LucideTrophy,
      LucideUndo2,
      LucideUpload,
      LucideWifiOff,
      LucideWrench,
      LucideX,
      LucideZap,
      LucideKeyRound,
    ),
    provideMarkdown({
      loader: HttpClient,
      markedOptions: {
        provide: MARKED_OPTIONS,
        useValue: {
          breaks: false,
          gfm: true,
          pedantic: false,
        },
      },
      mermaidOptions: {
        provide: MERMAID_OPTIONS,
        useValue: {
          startOnLoad: true,
          theme: 'dark',
          look: 'classic',
          flowchart: { curve: 'basis' },
          gantt: { useMaxWidth: true },
        },
      },
    }),
  ],
};
